# Welcome to Numpy

In [1]:
import numpy as np

In [2]:
myarr = np.array([[3,6,32,7]], np.int64)

In [3]:
myarr[0,1]

6

In [4]:
myarr.shape

(1, 4)

In [5]:
myarr.dtype

dtype('int64')

In [6]:
myarr[0,2]=65


In [7]:
myarr

array([[ 3,  6, 65,  7]], dtype=int64)

In [8]:
np.array({12,76,76,12})

array({12, 76}, dtype=object)

In [9]:
zeros = np.zeros((2,5))

In [10]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
np.linspace(1,5,4)

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [12]:
np.empty((4,6))

array([[6.23042070e-307, 1.42417221e-306, 1.37961641e-306,
        1.39071445e-307, 8.01097889e-307, 1.78020169e-306],
       [7.56601165e-307, 1.02359984e-306, 1.33510679e-306,
        2.22522597e-306, 1.33511018e-306, 6.23057689e-307],
       [1.86921279e-306, 8.90098127e-307, 1.78020848e-306,
        1.60219035e-306, 1.42418172e-306, 2.04712906e-306],
       [7.56589622e-307, 1.11258277e-307, 8.90111708e-307,
        2.11389826e-307, 1.11260619e-306, 2.22522596e-306]])

In [13]:
np.empty_like(zeros)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
arr = np.arange(16
               )

In [15]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [16]:
arr = arr.reshape(4,4)

In [17]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [18]:
arr = arr.ravel()

In [19]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [20]:
x = [[1,2,3], [4,51,6],[10,0,9]]

In [21]:
ar = np.array(x)

In [22]:
ar

array([[ 1,  2,  3],
       [ 4, 51,  6],
       [10,  0,  9]])

In [23]:
ar.sum(axis=0)

array([15, 53, 18])

In [24]:
ar.sum(axis=1)

array([ 6, 61, 19])

In [25]:
ar.T

array([[ 1,  4, 10],
       [ 2, 51,  0],
       [ 3,  6,  9]])

In [26]:
ar.flat

In [27]:
for item in ar.flat:
    print (item)


1
2
3
4
51
6
10
0
9


In [28]:
ar.ndim

2

In [29]:
ar.size

9

In [30]:
ar.nbytes

36

In [31]:
one = np.array([1,3,56,45,9,0])

In [32]:
one.argmax()

2

In [33]:
one.argmin()

5

In [34]:
one.argsort()

array([5, 0, 1, 4, 3, 2], dtype=int64)

In [35]:
ar

array([[ 1,  2,  3],
       [ 4, 51,  6],
       [10,  0,  9]])

In [36]:
ar.argmin()

7

In [37]:
ar.argmax()

4

In [38]:
ar.argsort()

array([[0, 1, 2],
       [0, 2, 1],
       [1, 2, 0]], dtype=int64)

In [39]:
ar.argmax(axis=0)

array([2, 1, 2], dtype=int64)

In [40]:
ar.argmin(axis=0)

array([0, 2, 0], dtype=int64)

In [41]:
ar.argmin(axis=1)

array([0, 0, 1], dtype=int64)

In [42]:
ar.argmax(axis=1)

array([2, 1, 0], dtype=int64)

In [43]:
ar

array([[ 1,  2,  3],
       [ 4, 51,  6],
       [10,  0,  9]])

In [44]:
np.where(ar>5)

(array([1, 1, 2, 2], dtype=int64), array([1, 2, 0, 2], dtype=int64))

In [45]:
np.count_nonzero(ar)

8

In [46]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 2], dtype=int64))