In [1]:
import numpy as np

In [2]:
a = np.array([[1,2,3],
             [4,5,6]])

In [3]:
a.sum(axis=0)

array([5, 7, 9])

In [4]:
b = np.array([[7,8,9],[2,8,0]])

In [10]:
a.dot(b.T)

array([[ 50,  18],
       [122,  48]])

In [11]:
len(dir(np))

606

In [14]:
np.cross(a,b)

array([[ -6,  12,  -6],
       [-48,  12,  22]])

In [15]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
np.sort(b)

array([[7, 8, 9],
       [0, 2, 8]])

In [17]:
np.sort(b, axis=0)

array([[2, 8, 0],
       [7, 8, 9]])